const data = [
  {
    img: "https://us.pandora.net/dw/image/v2/AAVX_PRD/on/demandware.static/-/Sites-pandora-master-catalog/default/dwe8f8d8df/productimages/singlepackshot/193422C01_RGB.jpg?sw=440&sh=440&sm=fit&sfrm=png&bgcolor=F5F5F5",
    title: "Disney Villains Evil Queen Ring",
    color: "red",
    price: "$95.00",
    category: "rings",
  },
  {
    img: "https://us.pandora.net/dw/image/v2/AAVX_PRD/on/demandware.static/-/Sites-pandora-master-catalog/default/dwc03eb5c5/productimages/singlepackshot/189655C01_RGB.jpg?sw=440&sh=440&sm=fit&sfrm=png&bgcolor=F5F5F5",
    title: "Pandora ME Black Enamel Ring",
    color: "black",
    price: "$90.00",
    category: "rings",
  },
  {
    img: "https://us.pandora.net/dw/image/v2/AAVX_PRD/on/demandware.static/-/Sites-pandora-master-catalog/default/dw632c6fe0/productimages/main/199655C03_RGB.jpg?sw=440&sh=440&sm=fit&sfrm=png&bgcolor=F5F5F5",
    title: "FINAL SALE - Pandora ME Laser Green Ring",
    color: "green",
    price: "$20.99",
    category: "rings",
  },

  {
    img: "https://us.pandora.net/dw/image/v2/AAVX_PRD/on/demandware.static/-/Sites-pandora-master-catalog/default/dw9c320163/productimages/singlepackshot/599662C00_RGB.jpg?sw=440&sh=440&sm=fit&sfrm=png&bgcolor=F5F5F5",
    title: "Pandora ME Small-Link Chain Bracelet",
    color: "nocolor",
    price: "$70.00",
    category: "bracelets",
  },
  {
    img: "https://us.pandora.net/dw/image/v2/AAVX_PRD/on/demandware.static/-/Sites-pandora-master-catalog/default/dw8259463c/productimages/main/590745CBK-D_RGB.jpg?sw=440&sh=440&sm=fit&sfrm=png&bgcolor=F5F5F5",
    title: "Pandora Moments Double Black Leather Bracelet",
    color: "black",
    price: "$70.00",
    category: "bracelets",
  },
  {
    img: "https://us.pandora.net/dw/image/v2/AAVX_PRD/on/demandware.static/-/Sites-pandora-master-catalog/default/dw676849b1/productimages/singlepackshot/592793C00_RGB.jpg?sw=440&sh=440&sm=fit&sfrm=png&bgcolor=F5F5F5",
    title: "Pandora ME Metal Bead & Link Chain Bracelet",
    color: "nocolor",
    price: "$115.00",
    category: "bracelets",
  },
  {
    img: "https://us.pandora.net/dw/image/v2/AAVX_PRD/on/demandware.static/-/Sites-pandora-master-catalog/default/dw6a044524/productimages/singlepackshot/592790C01_RGB.jpg?sw=440&sh=440&sm=fit&sfrm=png&bgcolor=F5F5F5",
    title: "Pandora Moments Round Clasp Blue Braided Leather Bracelet",
    color: "blue",
    price: "$70.00",
    category: "bracelets",
  },
  {
    img: "https://us.pandora.net/dw/image/v2/AAVX_PRD/on/demandware.static/-/Sites-pandora-master-catalog/default/dwf01546d6/productimages/singlepackshot/569662C00_RGB.jpg?sw=440&sh=440&sm=fit&sfrm=png&bgcolor=F5F5F5",
    title: "Pandora ME Small-Link Chain Bracelet",
    color: "nocolor",
    price: "$200.00",
    category: "bracelets",
  },
  {
    img: "https://us.pandora.net/dw/image/v2/AAVX_PRD/on/demandware.static/-/Sites-pandora-master-catalog/default/dwfd15fc37/productimages/singlepackshot/592340C00_RGB.jpg?sw=440&sh=440&sm=fit&sfrm=png&bgcolor=F5F5F5",
    title: "Pandora ME XS-Link Chain Bracelet",
    color: "nocolor",
    price: "$70.00",
    category: "bracelets",
  },

  {
    img: "https://us.pandora.net/dw/image/v2/AAVX_PRD/on/demandware.static/-/Sites-pandora-master-catalog/default/dw869f2741/productimages/singlepackshot/799183C00_RGB.jpg?sw=440&sh=440&sm=fit&sfrm=png&bgcolor=F5F5F5",
    title: "Openwork Sun, Stars & Moon Charm",
    color: "nocolor",
    price: "$25.00",
    category: "charms",
  },
  {
    img: "https://us.pandora.net/dw/image/v2/AAVX_PRD/on/demandware.static/-/Sites-pandora-master-catalog/default/dw155b0c39/productimages/main/797456_RGB.jpg?sw=440&sh=440&sm=fit&sfrm=png&bgcolor=F5F5F5",
    title: "Letter B Alphabet Charm",
    color: "nocolor",
    price: "$45.00",
    category: "charms",
  },
  {
    img: "https://us.pandora.net/dw/image/v2/AAVX_PRD/on/demandware.static/-/Sites-pandora-master-catalog/default/dw472c4c6a/productimages/main/797469_RGB.jpg?sw=440&sh=440&sm=fit&sfrm=png&bgcolor=F5F5F5",
    title: "Letter O Alphabet Charm",
    color: "nocolor",
    price: "$45.00",
    category: "charms",
  },
  {
    img: "https://us.pandora.net/dw/image/v2/AAVX_PRD/on/demandware.static/-/Sites-pandora-master-catalog/default/dwa9ba74a4/productimages/singlepackshot/NAMPS0660.jpg?sw=440&sh=440&sm=fit&sfrm=png&bgcolor=F5F5F5",
    title: "Disney Villains Charm Trio",
    color: "red",
    price: "$245.00",
    category: "charms",
  },
  {
    img: "https://us.pandora.net/dw/image/v2/AAVX_PRD/on/demandware.static/-/Sites-pandora-master-catalog/default/dw02a84e67/productimages/singlepackshot/763421C01_RGB.jpg?sw=440&sh=440&sm=fit&sfrm=png&bgcolor=F5F5F5",
    title: "Disney Villains Evil Queen Apple Dangle Charm",
    color: "red",
    price: "$85.00",
    category: "charms",
  },
  {
    img: "https://us.pandora.net/dw/image/v2/AAVX_PRD/on/demandware.static/-/Sites-pandora-master-catalog/default/dw06e77e52/productimages/singlepackshot/793420C01_RGB.jpg?sw=440&sh=440&sm=fit&sfrm=png&bgcolor=F5F5F5",
    title: "Disney Villains Queen of Hearts Double Dangle Charm",
    color: "red",
    price: "$75.00",
    category: "charms",
  },
  {
    img: "https://us.pandora.net/dw/image/v2/AAVX_PRD/on/demandware.static/-/Sites-pandora-master-catalog/default/dw75b10fe8/productimages/main/791993CZ_RGB.jpg?sw=440&sh=440&sm=fit&sfrm=png&bgcolor=F5F5F5",
    title: "Moon & Blue Sky Dangle Charm",
    color: "blue",
    price: "$70.00",
    category: "charms",
  },
  {
    img: "https://us.pandora.net/dw/image/v2/AAVX_PRD/on/demandware.static/-/Sites-pandora-master-catalog/default/dwa9ba74a4/productimages/singlepackshot/NAMPS0660.jpg?sw=440&sh=440&sm=fit&sfrm=png&bgcolor=F5F5F5",
    title: "Disney Villains Charm Trio",
    color: "black",
    price: "$245.00",
    category: "charms",
  },
  {
    img: "https://us.pandora.net/dw/image/v2/AAVX_PRD/on/demandware.static/-/Sites-pandora-master-catalog/default/dw3090d646/productimages/singlepackshot/793423C01_RGB.jpg?sw=440&sh=440&sm=fit&sfrm=png&bgcolor=F5F5F5",
    title: "Disney Villains Maleficent Charm",
    color: "black",
    price: "$85.00",
    category: "charms",
  },
  {
    img: "https://us.pandora.net/dw/image/v2/AAVX_PRD/on/demandware.static/-/Sites-pandora-master-catalog/default/dwa8f20be4/productimages/singlepackshot/793424C01_RGB.jpg?sw=440&sh=440&sm=fit&sfrm=png&bgcolor=F5F5F5",
    title: "Disney Villains Cruella De Vil Charm",
    color: "black",
    price: "$85.00",
    category: "charms",
  },
  {
    img: "https://us.pandora.net/dw/image/v2/AAVX_PRD/on/demandware.static/-/Sites-pandora-master-catalog/default/dwcf04e216/productimages/singlepackshot/762299C01_RGB.jpg?sw=440&sh=440&sm=fit&sfrm=png&bgcolor=F5F5F5",
    title: "FINAL SALE - Pandora ME Faceted Star Mini Dangle Charm",
    color: "black",
    price: "$30.99",
    category: "charms",
  },
  {
    img: "https://us.pandora.net/dw/image/v2/AAVX_PRD/on/demandware.static/-/Sites-pandora-master-catalog/default/dw21108abb/productimages/singlepackshot/792754C01_RGB.jpg?sw=440&sh=440&sm=fit&sfrm=png&bgcolor=F5F5F5",
    title: "Disney Pixar Mike Wazowski Charm",
    color: "green",
    price: "$75.00",
    category: "charms",
  },
];

export default data;
